hfmarkets:
  config:
    bootstrapProperties: "bootstrap.ldn.simulation.properties"
    configurationS3UrlPrefix: 'Go/ConfigJSON-01Feb21-1522.json'
    maxVarLevel: 250k
    configurationS3Url: 's3://mfx-compass-customer-config/GO_MARKETS/GO_MARKETS_config-update.json.gz'
